spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: fuse
          resources:
            requests:
              cpu: "0.2"
              memory: 256Mi
            limits:
              cpu: "1.0"
              memory: 1024Mi
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"tomcat":{"max-threads":10}}}'
